INSERT INTO timetable.days
VALUES (DEFAULT, 'Понедельник', 1),
       (DEFAULT, 'Вторник', 1),
       (DEFAULT, 'Среда', 1),
       (DEFAULT, 'Четверг', 1),
       (DEFAULT, 'Пятница', 1),
       (DEFAULT, 'Суббота', 1),
       (DEFAULT, 'Воскресенье', 1),
       (DEFAULT, 'Понедельник', 2),
       (DEFAULT, 'Вторник', 2),
       (DEFAULT, 'Среда', 2),
       (DEFAULT, 'Четверг', 2),
       (DEFAULT, 'Пятница', 2),
       (DEFAULT, 'Суббота', 2),
       (DEFAULT, 'Воскресенье', 2)