INSERT INTO timetable.professors
VALUES (DEFAULT, 'Андрей', 'Игоревич', 'Фоломкин',
        'https://personalii.spmi.ru/ru/glossary/f/folomkin_andrey_igorevich'),
       (DEFAULT, 'Екатерина', 'Александровна', 'Самыловская', 'https://personalii.spmi.ru/ru/node/35801'),
       (DEFAULT, 'Анна', 'Эдуардовна', 'Коротаева',
        'https://personalii.spmi.ru/ru/glossary/k/korotaeva_anna_eduardovna'),
       (DEFAULT, 'Андрей', 'Викторович', 'Дорофеев',
        'https://personalii.spmi.ru/ru/glossary/d/dorofeev_andrey_viktorovich'),
       (DEFAULT, 'Дмитрий', 'Анатолиевич', 'Васильев',
        'https://personalii.spmi.ru/ru/glossary/v/vasilev_dmitriy_anatolevich'),
       (DEFAULT, 'Игорь', 'Викторович', 'Мальцев', 'https://personalii.spmi.ru/ru/glossary/m/malcev_igor_viktorovich'),
       (DEFAULT, 'Светлана', 'Александровна', 'Свешникова',
        'https://personalii.spmi.ru/ru/glossary/s/sveshnikova_svetlana_aleksandrovna'),
       (DEFAULT, 'Жанна', 'Васильевна', 'Бойко', 'https://personalii.spmi.ru/ru/glossary/b/boyko_zhanna_vasilevna'),
       (DEFAULT, 'Николай', 'Алексеевич', 'Вахнин',
        'https://personalii.spmi.ru/ru/glossary/v/vahnin_nikolay_alekseevich'),
       (DEFAULT, 'Юлия', 'Александровна', 'Александровна',
        'https://personalii.spmi.ru/ru/glossary/ya/yakovleva_yuliya_aleksandrovna'),
       (DEFAULT, 'Евгений', 'Владимирович', 'Катунцов',
        'https://personalii.spmi.ru/ru/glossary/k/katuncov_evgeniy_vladimirovich'),
       (DEFAULT, 'Наталья', 'Андреевна', 'Егоренкова',
        'https://personalii.spmi.ru/ru/glossary/e/egorenkova_natalya_andreevna'),
       (DEFAULT, 'Ассистент', '', '', '')