INSERT INTO professors
VALUES (1, 'Андрей', 'Игоревич', 'Фоломкин', 'https://personalii.spmi.ru/ru/glossary/f/folomkin_andrey_igorevich'),
       (2, 'Екатерина', 'Александровна', 'Самыловская', 'https://personalii.spmi.ru/ru/node/35801'),
       (3, 'Анна', 'Эдуардовна', 'Коротаева', 'https://personalii.spmi.ru/ru/glossary/k/korotaeva_anna_eduardovna'),
       (4, 'Андрей', 'Викторович', 'Дорофеев', 'https://personalii.spmi.ru/ru/glossary/d/dorofeev_andrey_viktorovich'),
       (5, 'Дмитрий', 'Анатолиевич', 'Васильев',
        'https://personalii.spmi.ru/ru/glossary/v/vasilev_dmitriy_anatolevich'),
       (6, 'Игорь', 'Викторович', 'Мальцев', 'https://personalii.spmi.ru/ru/glossary/m/malcev_igor_viktorovich'),
       (7, 'Светлана', 'Александровна', 'Свешникова',
        'https://personalii.spmi.ru/ru/glossary/s/sveshnikova_svetlana_aleksandrovna'),
       (8, 'Жанна', 'Васильевна', 'Бойко', 'https://personalii.spmi.ru/ru/glossary/b/boyko_zhanna_vasilevna'),
       (9, 'Николай', 'Алексеевич', 'Вахнин', 'https://personalii.spmi.ru/ru/glossary/v/vahnin_nikolay_alekseevich'),
       (10, 'Юлия', 'Александровна', 'Александровна',
        'https://personalii.spmi.ru/ru/glossary/ya/yakovleva_yuliya_aleksandrovna'),
       (11, 'Евгений', 'Владимирович', 'Катунцов',
        'https://personalii.spmi.ru/ru/glossary/k/katuncov_evgeniy_vladimirovich'),
       (12, 'Наталья', 'Андреевна', 'Егоренкова',
        'https://personalii.spmi.ru/ru/glossary/e/egorenkova_natalya_andreevna'),
       (13, 'Ассистент', '', '', '')